variables:
  PACKAGE_PATH: /go/src/pikabu-signaling
  DOCKER_HUB_REGISTRY_PATH: dermaster/pikabu-signaling

stages:
  - build
  - deploy

build:
  tags:
    - dev
  only:
    - master
  stage: build
  image: docker:18.09.2
  services:
    - docker:dind
  script:
    - docker login -u dermaster -p KFXB3UVFpB7tmnC
    - docker build -t $DOCKER_HUB_REGISTRY_PATH:latest .
    - docker push $DOCKER_HUB_REGISTRY_PATH:latest

deploy:
  tags:
    - dep
  only:
    - master
  dependencies:
    - build
  stage: deploy
  script:
    - docker login -u dermaster -p KFXB3UVFpB7tmnC
    - docker pull $DOCKER_HUB_REGISTRY_PATH:latest
    - docker stack deploy -c docker-stack.deploy.yml dermaster
