version: "3.7"
services:
  pikabu_signaling:
    image: dermaster/pikabu-signaling:latest
    volumes:
      - type: volume
        source: pikabu_signaling_volume
        target: /var/local
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
         cpus: "0.1"
         memory: 100M
    networks:
      - deploy_network
networks:
  deploy_network:
volumes:
  pikabu_signaling_volume:
    external: true
