version: "3.7"
services:
  pikabu_signaling:
    image: dermaster/pikabu-signaling-dev:latest
    volumes:
      - type: bind
        source: .
        target: /go/src/pikabu-signaling
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
         cpus: "1.0"
         memory: 1000M
    networks:
      - develop_network
networks:
  develop_network:
