// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package grpc

import (
	grpc "github.com/go-kit/kit/transport/grpc"
	endpoint "pikabu-signaling/signaling/pkg/endpoint"
	pb "pikabu-signaling/signaling/pkg/grpc/pb"
)

// NewGRPCServer makes a set of endpoints available as a gRPC AddServer
type grpcServer struct {
	register           grpc.Handler
	webRTCStartPlease  grpc.Handler
	webRTCAnswer       grpc.Handler
	webRTCAddCandidate grpc.Handler
}

func NewGRPCServer(endpoints endpoint.Endpoints, options map[string][]grpc.ServerOption) pb.SignalingServer {
	return &grpcServer{
		register:           makeRegisterHandler(endpoints, options["Register"]),
		webRTCAddCandidate: makeWebRTCAddCandidateHandler(endpoints, options["WebRTCAddCandidate"]),
		webRTCAnswer:       makeWebRTCAnswerHandler(endpoints, options["WebRTCAnswer"]),
		webRTCStartPlease:  makeWebRTCStartPleaseHandler(endpoints, options["WebRTCStartPlease"]),
	}
}
